### ISSUE TITLE
Cannot build release apk

### ISSUE THREAD

**Issue by D4nt4lion** [safaeean/react-native-scan-barcode#5]
Debug apk works fine but release throws the following error:

> Task :react-native-scan-barcode:verifyReleaseResources FAILED

```Execution failed for task ':react-native-scan-barcode:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/ec59d609cd27918eac378cb4ae002be0/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/ec59d609cd27918eac378cb4ae002be0/appcompat-1.0.2/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/ec59d609cd27918eac378cb4ae002be0/appcompat-1.0.2/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/ec59d609cd27918eac378cb4ae002be0/appcompat-1.0.2/res/values-v28/values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/ec59d609cd27918eac378cb4ae002be0/appcompat-1.0.2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/startX not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/startY not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/endX not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/endY not found.
         
     ERROR:/home/jg/.gradle/caches/transforms-2/files-2.1/23ceb1b3b667a22290f02140e3ed44a6/core-1.0.1/res/values/values.xml:126:5-132:25: AAPT: error: resource android:attr/offset not found.
```
react-native: 0.65.1
build tools: 30.0.3
AppCompat: 28.0.0

**Comment by yashshah9621** [comment]
Link:- https://githubmemory.com/repo/jamesisaac/react-native-background-task/issues/70

In node_modules/react-native-scan-barcode/android/build.gradle I changed:

compileSdkVersion 23 -> 28

And now it works ok.

**Comment by pistonsky** [comment]
Had the same. Just don't forget to commit that into your patch (run `cd android; ./gradlew clean` before this command, otherwise you will also commit all build artifacts):
```
npx patch-package react-native-scan-barcode
```

**Comment by Productivix** [comment]
hi , can not auto link , since in React-Native, we are in 0.68 on Android sdk 30 at least

**Comment by Productivix** [comment]
Hi, 
after some researches, I place the manual linking like : 
Manual linking

    In android/settings.gradle

    ...
    include ':react-native-scan-barcode', ':app'
    project(':react-native-scan-barcode').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-scan-barcode/android')

    In android/app/build.gradle

    ...
    dependencies {
        ...
        implementation project(':react-native-scan-barcode')
    }

    register module (in MainApplication.java) 
C:\Users\info\...\test_RN_scan\android\app\src\main\java\com\test_rn_scan

    Add the following import statement:

    import com.safaeean.barcodescanner.BarcodeScannerPackage;

    ...and then add BarcodeScannerPackage to exported package list (MainApplication.java#getPackages):

    public class MainApplication extends Application implements ReactApplication {
        // (...)

    @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          packages.add(new BarcodeScannerPackage());
          return packages;
        }

**--> but I get the following error message after a npx react-native run-android:** 
`
> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\react-native-scan-barcode\android\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-scan-barcode'.
> Could not find method compile() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.        

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\react-native-scan-barcode\android\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-scan-barcode'.
> Could not find method compile() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.        

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

    at makeError (C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\execa\index.js:174:9)
    at C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
`

what could we do please ?

**Comment by malzate** [comment]
> Hi, after some researches, I place the manual linking like : Manual linking
> 
> ```
> In android/settings.gradle
> 
> ...
> include ':react-native-scan-barcode', ':app'
> project(':react-native-scan-barcode').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-scan-barcode/android')
> 
> In android/app/build.gradle
> 
> ...
> dependencies {
>     ...
>     implementation project(':react-native-scan-barcode')
> }
> 
> register module (in MainApplication.java) 
> ```
> 
> C:\Users\info...\test_RN_scan\android\app\src\main\java\com\test_rn_scan
> 
> ```
> Add the following import statement:
> 
> import com.safaeean.barcodescanner.BarcodeScannerPackage;
> 
> ...and then add BarcodeScannerPackage to exported package list (MainApplication.java#getPackages):
> 
> public class MainApplication extends Application implements ReactApplication {
>     // (...)
> 
> @Override
>     protected List<ReactPackage> getPackages() {
>       @SuppressWarnings("UnnecessaryLocalVariable")
>       List<ReactPackage> packages = new PackageList(this).getPackages();
>       // Packages that cannot be autolinked yet can be added manually here, for example:
>       // packages.add(new MyReactNativePackage());
>       packages.add(new BarcodeScannerPackage());
>       return packages;
>     }
> ```
> 
> **--> but I get the following error message after a npx react-native run-android:** `
> 
> > Configure project :app
> > Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings 6 actionable tasks: 6 up-to-date
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\react-native-scan-barcode\android\build.gradle' line: 16
> * What went wrong:
>   A problem occurred evaluating project ':react-native-scan-barcode'.
> 
> > Could not find method compile() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\react-native-scan-barcode\android\build.gradle' line: 16
> * What went wrong:
>   A problem occurred evaluating project ':react-native-scan-barcode'.
> 
> > Could not find method compile() for arguments [com.google.zxing:core:3.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15s
> 
> ```
> at makeError (C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\execa\index.js:174:9)
> at C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\execa\index.js:278:16
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async runOnAllDevices (C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
> at async Command.handleAction (C:\Users\info\Documents\logiciels-windows\dev_RN-Node-GIT\test_rn_scan\node_modules\@react-native-community\cli\build\index.js:192:9)
> ```
> 
> info Run CLI with --verbose flag for more details. `
> 
> what could we do please ?

@Productivix 

go to the library folder on node modules

then android/build.gradle

check the dependencies
since the word  compile is deprecated library will not work, so change it to implementation

before:
dependencies {
    compile'com.google.zxing:core:3.2.1'
    compile"com.facebook.react:react-native:+"  // From node_modules
}

after the change:
dependencies {
    implementation 'com.google.zxing:core:3.2.1'
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

then it will work , check it out.

**Comment by Productivix** [comment]
Hi @safaeean , 
very good ! it works perfectly , thank you !
best regards 
William

**Comment by Productivix** [comment]
hi @safaeean , 
I made some tests ok , not sure it scans better, with the last lib 3.4.1 version of xzing so the with a dependencies in your build.gradle : 
`
dependencies {
    implementation 'com.google.zxing:core:3.4.1'
    implementation "com.facebook.react:react-native:+"  // From node_modules
}`
The build.gradle of MY project is the following where it works: 
`buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:4.1.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }`

I am not very good in gradle versions and integration for the moment, do we need to upgrade the skd version in your lib ?
How can I participate to propose a new request / upgrade ?
I would propose you edit a new version with thoses changes.
