### ISSUE TITLE
Import error using in a fresh React Native app using expo

### ISSUE THREAD

**Issue by neekfenwick** [safaeean/react-native-scan-barcode#6]
I'm a real newbie with React Native, trying to follow the `expo` basic app setup and then use this module in the app.  The error I get is:

```
"export 'default' (imported as 'Viewfinder') was not found in './Viewfinder'
  33 |   render() {
  34 |     let viewFinder = this.props.showViewFinder ? (
> 35 |       <Viewfinder
     |       ^
  36 |         backgroundColor={this.props.viewFinderBackgroundColor}
  37 |         color={this.props.viewFinderBorderColor}
  38 |         borderWidth={this.props.viewFinderBorderWidth}
./node_modules/react-native-scan-barcode/scan-barcode.js:74:27
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
  72 | };
  73 | 
> 74 | var RNBarcodeScannerView = requireNativeComponent('RNBarcodeScannerView', BarcodeScannerView, {
     |                           ^
  75 |   nativeOnly: {onChange: true}
  76 | });
  77 | 
```

The steps are:
- Install expo-cli and create a new expo app:
$ npm install -g expo-cli
$ expo init StockCountSimple
$ cd StockCountSimple
(choose basic Javascript app)
- Add this module with:
$ npm i --save react-native-scan-barcode
- Require the module in App.js:
import BarcodeScanner from 'react-native-scan-barcode';

Attempted fix
------------------

From what I know of ES6 modules, it's complaining that `export 'default' (imported as 'Viewfinder') was not found in './Viewfinder'` which means that this module's main `scan-barcode.js` file tries to import Viewfinder with `import Viewfinder from './Viewfinder';` but it didn't find an export of that name.  The last line in Viewfinder.js is:

`module.exports = Viewfinder;`

I've tried editing that to:

`export default Viewfinder;`

with no luck.

Is this some basic module syntax problem, or is my `expo` project somehow fundamentally misconfigured to use this module?

**Comment by neekfenwick** [comment]
The actual result of modifying the export statements is, in Viewfinder.js change last line to: `export default Viewfinder;` and in scan-barcode.js change last line to: `export default BarcodeScannerView;`

`npm start` output then reports:

```
"export 'requireNativeComponent' was not found in 'react-native-web/dist/index'
  72 | };
  73 | 
> 74 | var RNBarcodeScannerView = requireNativeComponent('RNBarcodeScannerView', BarcodeScannerView, {
     |                           ^
  75 |   nativeOnly: {onChange: true}
  76 | });
  77 | 
```

This seems to be referring to line 74 in scan-barcode.js which looks as in that error output.  The `package.json` created by the `expo-cli` contains:

```
    "react-native": "0.68.2",
    "react-native-web": "0.17.7"

```

Could the lines in scan-barcode.js that import `requireNativeComponent` from `react-native` and then use it somehow be incompatible with the versions in my project?

**Comment by Productivix** [comment]
hi , 
if you are in Expo, there is simpler , take 
import { BarCodeScanner } from "expo-barcode-scanner";
see [doc ](https://docs.expo.dev/versions/latest/sdk/bar-code-scanner/)

**Comment by neekfenwick** [comment]
Thanks @Productivix you're right, that module seems to work fine.  As a relative React Native newbie I'm finding the different ecosystems of software rather confusing :) I'll close this issue as it seems irrelevant, this module is never expected to work with Expo.
