### ISSUE TITLE
is this package support iOS ?

### ISSUE THREAD

**Issue by ssathishppm** [safaeean/react-native-scan-barcode#8]

**Comment by Productivix** [comment]
"A barcode scanner component for react native android", so no iOS

**Comment by ssathishppm** [comment]
@Productivix Can we expect for iOS support in upcoming releases ?

**Comment by Productivix** [comment]
don't think so, but you'd rather ask the package owner.

**Comment by ssathishppm** [comment]
@safaeean

**Comment by safaeean** [comment]
It only works on Android

**Comment by safaeean** [comment]
For iOS you can use https://github.com/lwansbrough/react-native-camera
